### ISSUE TITLE
Cell overflow. Writing to builder is not possible since after operation there would be more than 1023 bits or 4 references.

### ISSUE THREAD

**Issue by lumpov** [supadupadao/jetton#8]
Словил задав description 368 байт, что больше 1 ячейки. Использование 4 references позволит увеличить размер поля description? Если сможете, реализуйте пжлст, я не смогу на tact.

**Comment by ya7on** [comment]
Спасибо за ишью! Посмотрю что можно с этим сделать

**Comment by ya7on** [comment]
В #9 исправил

Ниже код как в файле `scripts/deployJettonMaster.ts`. Пример как можно задать описание жетона длиной 3015 байт и чтобы его корректно обрабатывали tonviewer и tonscan
```js
await jettonMaster.send(
  provider.sender(),
  {
      value: toNano('0.05'),
  },
  {
      $$type: 'JettonInit',
      query_id: 0n,
      jetton_name: beginCell().storeStringRefTail('Jetton name').asSlice(),
      jetton_description: beginCell().storeStringRefTail('Long' + ' long '.repeat(1000) + 'description').asSlice(),
      jetton_symbol: beginCell().storeStringRefTail('SMBL').asSlice(),
      max_supply: toNano(1337),
  }
);
```
